name: "jaffle_shop"
version: "0.1"

config-version: 2
dbt-cloud:
  project-id: 336480

profile: "jaffle_shop"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']

models:
  jaffle_shop:
    materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table
      +required_docs: true
      +required_tests: {"unique.*|not_null|relationships.*": 2}

tests:
  +store_failures: true
  dbt_project_evaluator:
    +severity: "{{ env_var('DBT_PROJECT_EVALUATOR_SEVERITY', 'warn') }}"

seeds:
  dbt_project_evaluator:
      dbt_project_evaluator_exceptions:
        +enabled: false

vars:
  dbt_project_evaluator:
    documentation_coverage_target: 75
    test_coverage_target: 75

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues(format='csv') }}"