name: "jaffle_shop"
version: "0.1"

config-version: 2
dbt-cloud:
  project-id: 336480

profile: "jaffle_shop"

model-paths: ["models", "docs"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
    +persist_docs: 
      relation: false
      columns: true
    materialized: table
    docs_background_color: white

    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      +required_docs: true
      +required_tests: {"unique.*|not_null|relationships.*": 2}
      +tags: ['clone_test_active']
    clone:
      +tags: ['clone_schema']
      +labels: {'visible_to_users': 'false'}
      +materialized: table
      +schema: clone

tests:
  +store_failures: true
  dbt_project_evaluator:
    +severity: "{{ env_var('DBT_PROJECT_EVALUATOR_SEVERITY', 'warn') }}"
  jaffle_shop:
    assert_stg_customer_compare_all_columns:
      +severity: warn
      +enabled: false
    assert_fct_orders_compare_all_columns_with_baseline:
      +severity: error
      +enabled: false
    assert_fct_orders_compare_all_columns:
      +severity: error
      +enabled: false
    assert_dim_customers_compare_all_columns:
      +enabled: false
      

seeds:
  dbt_project_evaluator:
      dbt_project_evaluator_exceptions:
        +enabled: false

vars:
  dbt_project_evaluator:
    documentation_coverage_target: 80
    test_coverage_target: 80

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues(format='csv') }}"