version: 2

exposures:
  - name: monthly_sell_growth
    type: dashboard
    label: Monthly Sells Report
    url: https://www.cognizant.com/cogsellreport.aspx
    description: Report that show the growth sells for each month of the current year.
    depends_on:
      - "ref('dim_customers')"
      - "ref('fct_orders')"
    owner:
      name: Emerson Ferreira
      email: emerson.ferreira@cognizant.com